#!/usr/bin/env python2

##
# PyCross
# https://github.com/leosartaj/PyCross.git
#
# Copyright (c) 2014 Sartaj Singh
# Licensed under the MIT license.
##

from gui.pycrossGUIClass import pycrossGUIClass
import gtk

if __name__ == '__main__':
    app = pycrossGUIClass()
    gtk.main()
