#!/usr/bin/env python2

##
# PyCross
# https://github.com/leosartaj/PyCross.git
#
# Copyright (c) 2014 Sartaj Singh
# Licensed under the MIT license.
##

import argparse

# for gui
from gui.pycrossGUIClass import pycrossGUIClass
import gtk

try:
    from PyCross import __desc__ # try to get version number
except ImportError:
    __desc__ = 'UNKNOWN'

def parse_args():
    parser = argparse.ArgumentParser(description='Classic Tic-Tac-Toe game')

    help = "Current version of PyCross"
    parser.add_argument('--version', '-v',  action='version', help=help, version=__desc__)

    args = parser.parse_args()

    return args

if __name__ == '__main__':
    args = parse_args()

    app = pycrossGUIClass()
    gtk.main()
